ProjetFinal_6224745/Models/Mouvement.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProjetFinal_6224745.Models;

[Table("Mouvement", Schema = "Appareil")]
public partial class Mouvement
{
    [Key]
    [Column("MouvementID")]
    public int MouvementId { get; set; }

    [StringLength(50)]
    public string? Nom { get; set; }

    [StringLength(1)]
    public string? Difficulte { get; set; }

    [Column(TypeName = "decimal(3, 1)")]
    public decimal Valeur { get; set; }

    [StringLength(255)]
    public string Description { get; set; } = null!;

    [Column("AgreID")]
    public int AgreId { get; set; }

    [ForeignKey("AgreId")]
    [InverseProperty("Mouvements")]
    public virtual Agre Agre { get; set; } = null!;

    [InverseProperty("Mouvement")]
    public virtual ICollection<Performance> Performances { get; set; } = new List<Performance>();
}

ProjetFinal_6224745/Controllers/AgresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Security.Principal;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjetFinal_6224745.Data;
using ProjetFinal_6224745.Models;
using ProjetFinal_6224745.ViewModels;

namespace ProjetFinal_6224745.Controllers
{
    public class AgresController : Controller
    {
        private readonly BdGymnastiqueContext _context;

        public AgresController(BdGymnastiqueContext context)
        {
            _context = context;
        }

        // GET: Agres
        public async Task<IActionResult> Index()
        {
            ViewData["utilisateur"] = "Visisteur";
            IIdentity? identite = HttpContext.User.Identity;
            if (identite != null && identite.IsAuthenticated)
            {
                string pseudo = HttpContext.User.FindFirstValue(ClaimTypes.Name);
                Utilisateur? utilisateur = await _context.Utilisateurs.FirstOrDefaultAsync(x => x.Pseudonyme == pseudo);
                if (utilisateur != null)
                {
                    ViewData["utilisateur"] = utilisateur.Pseudonyme;
                }
            }
            return View(await _context.Agres.ToListAsync());
        }

        // GET: Agres/Details/6
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var agreDetails = await _context.VwDetailAgres
                .Where(m => m.AgreId == id)
                .ToListAsync();

            if (agreDetails == null || !agreDetails.Any())
            {
                return NotFound("Il n'y a pas de details pour cet appareil");
            }

            var AgreSlected = await _context.Agres.Where(x => x.AgreId == id).FirstAsync();
            

            var afficheImage = await _context.Affiches
                .Where(x => x.AgreId == id)
                .Select(x => x.AfficheContent == null ? null : $"data:image/png;base64,{Convert.ToBase64String(x.AfficheContent)}")
                .FirstOrDefaultAsync();
            AgresAfficheViewModel vm = new AgresAfficheViewModel()
            {
                DetailAgre = agreDetails,
                AfficheContent = afficheImage,
                Agres = AgreSlected
            };

            return View(vm);
        }

        // GET: Agres/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Agres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AgreId,Nom")] Agre agre)
        {
            if (ModelState.IsValid)
            {
                _context.Add(agre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(agre);
        }

        // GET: Agres/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var agre = await _context.Agres.FindAsync(id);
            if (agre == null)
            {
                return NotFound();
            }
            return View(agre);
        }

        // POST: Agres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AgreId,Nom")] Agre agre)
        {
            if (id != agre.AgreId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(agre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AgreExists(agre.AgreId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(agre);
        }

        // GET: Agres/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var agre = await _context.Agres
                .FirstOrDefaultAsync(m => m.AgreId == id);
            if (agre == null)
            {
                return NotFound();
            }

            return View(agre);
        }

        // POST: Agres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var agre = await _context.Agres.FindAsync(id);
            if (agre != null)
            {
                _context.Agres.Remove(agre);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AgreExists(int id)
        {
            return _context.Agres.Any(e => e.AgreId == id);
        }
    }
}

ProjetFinal_6224745/Controllers/MouvementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using ProjetFinal_6224745.Data;
using ProjetFinal_6224745.Models;

namespace ProjetFinal_6224745.Controllers
{
    public class MouvementsController : Controller
    {
        private readonly BdGymnastiqueContext _context;

        public MouvementsController(BdGymnastiqueContext context)
        {
            _context = context;
        }

        // GET: Mouvements
        public async Task<IActionResult> Index()
        {
            var bdGymnastiqueContext = _context.Mouvements.Include(m => m.Agre);
            return View(await bdGymnastiqueContext.ToListAsync());
        }
        [Authorize]
        // GET: Mouvements Filtré
        public async Task<IActionResult> FiltrageMouvements(string agre, string difficulte)
        {
            var isSaut = agre == "Saut de cheval";

            object difficulteParam;

            if (isSaut)
            {
                difficulteParam = "Tous"; // Valeur spéciale pour le saut
            }
            else
            {
                // 2. Gérer correctement les valeurs null avec DBNull
                difficulteParam = !string.IsNullOrEmpty(difficulte) ? (object)difficulte : DBNull.Value;
            }

            // 3. Créer les paramètres SQL correctement typés
            var parameters = new[]
            {
                new SqlParameter("@Agres", string.IsNullOrEmpty(agre) ? DBNull.Value : (object)agre),
                new SqlParameter("@Difficulte", difficulteParam)
            };

            var result = await _context.MouvementFiltreResults
                .FromSqlRaw("EXEC Appareil.usp_FiltrageMouvements @Agres, @Difficulte", parameters)
                .AsNoTracking()
                .ToListAsync();

             return View(result);
        }

        // GET: Mouvements/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mouvement = await _context.Mouvements
                .Include(m => m.Agre)
                .FirstOrDefaultAsync(m => m.MouvementId == id);
            if (mouvement == null)
            {
                return NotFound();
            }

            return View(mouvement);
        }

        // GET: Mouvements/Create
        public IActionResult Create()
        {
            ViewData["AgreId"] = new SelectList(_context.Agres, "AgreId", "AgreId");
            return View();
        }

        // POST: Mouvements/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MouvementId,Nom,Difficulte,Valeur,Description,AgreId")] Mouvement mouvement)
        {
            if (ModelState.IsValid)
            {
                _context.Add(mouvement);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AgreId"] = new SelectList(_context.Agres, "AgreId", "AgreId", mouvement.AgreId);
            return View(mouvement);
        }

        // GET: Mouvements/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mouvement = await _context.Mouvements.FindAsync(id);
            if (mouvement == null)
            {
                return NotFound();
            }
            ViewData["AgreId"] = new SelectList(_context.Agres, "AgreId", "AgreId", mouvement.AgreId);
            return View(mouvement);
        }

        // POST: Mouvements/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MouvementId,Nom,Difficulte,Valeur,Description,AgreId")] Mouvement mouvement)
        {
            if (id != mouvement.MouvementId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mouvement);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MouvementExists(mouvement.MouvementId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AgreId"] = new SelectList(_context.Agres, "AgreId", "AgreId", mouvement.AgreId);
            return View(mouvement);
        }

        // GET: Mouvements/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mouvement = await _context.Mouvements
                .Include(m => m.Agre)
                .FirstOrDefaultAsync(m => m.MouvementId == id);
            if (mouvement == null)
            {
                return NotFound();
            }

            return View(mouvement);
        }

        // POST: Mouvements/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var mouvement = await _context.Mouvements.FindAsync(id);
            if (mouvement != null)
            {
                _context.Mouvements.Remove(mouvement);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MouvementExists(int id)
        {
            return _context.Mouvements.Any(e => e.MouvementId == id);
        }
    }
}

ProjetFinal_6224745/Views/Mouvements/Create.cshtml
@model ProjetFinal_6224745.Models.Mouvement

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Mouvement</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Difficulte" class="control-label"></label>
                <input asp-for="Difficulte" class="form-control" />
                <span asp-validation-for="Difficulte" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Valeur" class="control-label"></label>
                <input asp-for="Valeur" class="form-control" />
                <span asp-validation-for="Valeur" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AgreId" class="control-label"></label>
                <select asp-for="AgreId" class ="form-control" asp-items="ViewBag.AgreId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjetFinal_6224745/Views/Mouvements/Delete.cshtml
@model ProjetFinal_6224745.Models.Mouvement

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Mouvement</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Difficulte)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Difficulte)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Valeur)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Valeur)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Agre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Agre.AgreId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MouvementId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ProjetFinal_6224745/Views/Mouvements/Details.cshtml
@model ProjetFinal_6224745.Models.Mouvement

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Mouvement</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Difficulte)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Difficulte)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Valeur)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Valeur)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Agre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Agre.AgreId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.MouvementId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ProjetFinal_6224745/Views/Mouvements/Edit.cshtml
@model ProjetFinal_6224745.Models.Mouvement

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Mouvement</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MouvementId" />
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Difficulte" class="control-label"></label>
                <input asp-for="Difficulte" class="form-control" />
                <span asp-validation-for="Difficulte" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Valeur" class="control-label"></label>
                <input asp-for="Valeur" class="form-control" />
                <span asp-validation-for="Valeur" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AgreId" class="control-label"></label>
                <select asp-for="AgreId" class="form-control" asp-items="ViewBag.AgreId"></select>
                <span asp-validation-for="AgreId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjetFinal_6224745/Views/Mouvements/FiltrageMouvements.cshtml
@model IEnumerable<ProjetFinal_6224745.Models.MouvementFiltreResult>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>List des mouvements filtrés</h1>

<p>
    <a asp-controller="Agres" asp-action="Index">Retour à l'accueuil</a>
</p>
<div class="mb-3">
    <form asp-action="FiltrageMouvements" method="get">
    <label for="agre">Nom de l'agrès :</label>
    <select name="agre">
        <option value="">-- Sélectionnez --</option>
        <option value="Sol">Sol</option>
        <option value="Cheval d’arçons">Cheval d’arçons</option>
        <option value="Anneaux">Anneaux</option>
        <option value="Saut de cheval">Saut de cheval</option>
        <option value="Barres Parallèles">Barres Parallèles</option>
        <option value="Barre fixe">Barre fixe</option>
    </select>

    <label for="difficulte">Difficulté :</label>
    <input type="text" name="difficulte" placeholder="Ex : Tous, A, B, C, etc.">

    <input type="submit" value="Filtrer">
</form>
</div>
<a asp-controller="Mouvements" asp-action="Index">Supprimer les filtres</a>
<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.NomMouvement)</th>
            <th>@Html.DisplayNameFor(model => model.Difficulte)</th>
            <th>@Html.DisplayNameFor(model => model.Valeur)</th>
            <th>@Html.DisplayNameFor(model => model.Description)</th>
            <th>Nom de l'agrès'</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.NomMouvement)</td>
                <td>@Html.DisplayFor(modelItem => item.Difficulte)</td>
                <td>@Html.DisplayFor(modelItem => item.Valeur)</td>
                <td>@Html.DisplayFor(modelItem => item.Description)</td>
                <td>@Html.DisplayFor(modelItem => item.NomAgre)</td>
            </tr>
        }
    </tbody>
</table>

ProjetFinal_6224745/Views/Mouvements/Index.cshtml
@model IEnumerable<ProjetFinal_6224745.Models.Mouvement>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>List des mouvements</h1>

<p>
    <a asp-controller="Agres" asp-action="Index">Retour à l'accueuil</a>
</p>
<div class="mb-3">
    <form asp-action="FiltrageMouvements" method="get">
        <label for="agre">Nom de l'agrès :</label>
        <select name="agre">
            <option value="">-- Sélectionnez --</option>
            <option value="Sol">Sol</option>
            <option value="Cheval d’arçons">Cheval d’arçons</option>
            <option value="Anneaux">Anneaux</option>
            <option value="Saut de cheval">Saut de cheval</option>
            <option value="Barres Parallèles">Barres Parallèles</option>
            <option value="Barre fixe">Barre fixe</option>
        </select>

        <label for="difficulte">Difficulté :</label>
        <input type="text" name="difficulte" placeholder="Ex : Tous, A, B, C, etc.">

        <input type="submit" value="Filtrer">
    </form>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Difficulte)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Valeur)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Agre.Nom)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Difficulte)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Valeur)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Agre.Nom)
            </td>
        </tr>
}
    </tbody>
</table>